### ISSUE TITLE
ZstdSharp.ZstdException: Dictionary mismatch

### ISSUE THREAD

**Issue by mlc2020** [ArchLeaders/MalsMerger#2]
Struggling to get this to work using Linux version (on steam deck). Merge command finds input (romfs dump & mod's romfs folder) and output folders but can't progress further due to the error below.
![Screenshot_20240404_223641](https://github.com/ArchLeaders/MalsMerger/assets/56771146/13451b92-348f-4693-96a9-f392c217392d)

**Comment by ArchLeaders** [comment]
It likely means your game paths aren't configured.

If they are, then something is wrong with your `ZsDic.pack.zs` file.

**Comment by mlc2020** [comment]
What do you mean by your first point? How do you configure your game paths?

Otherwise, I will attempt to redump the game.

**Comment by ArchLeaders** [comment]
Because this is designed to be used with TKMM, there's no great way to configure them through the app, but it's just a json file in `/local/share/Totk/config.json` with the following contents:

```json
{
  "GamePath": "/path/to/romfs"
}
```

**Comment by mlc2020** [comment]
The config was the issue. Thanks!
